platforms:
- name: T2
  repo: https://github.com/tuya/TuyaOpen-T2
  branch: master
  commit: 910bc3c93de3c988f7edca7f4c0b8d9d95c2d7c7

- name: T3
  repo: https://github.com/tuya/TuyaOpen-T3
  branch: master
  commit: a8425530dcf866a24f4a992056bc9993a2742c10

- name: LINUX
  repo: https://github.com/tuya/TuyaOpen-ubuntu
  branch: platform_ubuntu
  commit: 811c996c040fd0fbcdb96ea2e36885326b9b927d

- name: T5AI
  repo: https://github.com/tuya/TuyaOpen-T5AI
  branch: master
  commit: 57f813c9bc0bf3a7561e3f0e306dae657bac819d

# MERGE-TODO: verify ESP32 platform commit vs master
- name: ESP32
  repo: https://github.com/tuya/TuyaOpen-esp32
  branch: dev
  commit: 0422216594c10a0a0a45a5ca99dfb4b690120663

- name: LN882H
  repo: https://github.com/tuya/TuyaOpen-ln882h
  branch: master
  commit: 3132855d1873ce065059e3647be58f6b608c3a1f

- name: BK7231X
  repo: https://github.com/tuya/TuyaOpen-bk7231x
  branch: master
  commit: 8ad5239fd9482ad66eced11677a5e64dcb5e9b4b

- name: GD32
  repo: https://github.com/tuya/TuyaOpen-GigaDevice
  branch: master
  commit: 039e42e478c5c41fa2ef831a74a42247a3dc5613
